### ISSUE TITLE
SWOT

### ISSUE THREAD

**Issue by topenkoff** [stankin/oop-app#16]
**Как:** аналитик
**Хочу:** видеть отображение полностью описанной в базе данных информации для SWOT таблицы
**Чтобы:** проводить стратегическое планирование 

**Приемочный тест:** в экранной форме таблицы можно увидеть все необходимые данные
**Эпик:** [задача 8](https://github.com/stankin/oop-2018/wiki/Задача-№8-(SWOT))

**Comment by Highlanderstankin** [comment]
Подзадачи дизайна:

- [ ] #18   
- [ ] #19  
- [ ] #20  

Подзадачи процедур:
- [ ] #21  
- [ ] #22  

Подзадачи тестирования:

- [ ] #23 
- [ ] #24  
- [ ] #25
