### ISSUE TITLE
создание сайта

### ISSUE THREAD

**Issue by AbakumtsevRoman** [stankin/oop-app#42]
реализовать сайт исходя из макета, требований к именам страниц и т.д.

**Comment by vanya97** [comment]
Алгоритм работы с системой:
1. Пользователь вводит данные с диаграммы IDEF0.
2. После нажатия кнопки введеные данные передаются в обработчик.
3. Обработчик на основе полученных данных строит диаграмму классов.
4. Полученная диаграмма выводится на экран.

**Comment by vanya97** [comment]
[


](url)

**Comment by AbakumtsevRoman** [comment]
расположение файлов:
https://github.com/AbakumtsevRoman/proekt.github.io/tree/master/5-7

**Comment by AbakumtsevRoman** [comment]
рабочая страница ввода данных:
https://abakumtsevroman.github.io/proekt.github.io/5-7/lab.html
