### ISSUE TITLE
Диаграммы IDF0 и диаграммы классов

### ISSUE THREAD

**Issue by ghost** [stankin/oop-app#96]
Как аналитик я хочу получить интерфейс для  корректного отображения диаграммы IDF0  и  диаграммы классов UML, с целью дать пользователю возможность увидеть и сравнить их, а так же обеспечить возможность их дальнейшего использования 
приемочный тест: диаграммы корректно отображаются на экране (поочередно или одновременно)

**Comment by ghost** [comment]
Архитектор:
#97 
#98 
Дизайнер:
#99 
#100 
#102 
Программист:
#101 
#103 
#105 
#106 
Тестировщик:
#107

**Comment by VarvariucA** [comment]
https://ivangpn.github.io/site.github.io/#PageHome.xaml
